### ISSUE TITLE
(AWS) Lambda auf Edge umstellen

### ISSUE THREAD

**Issue by marcmarder** [marcmarder/CloudsHandsOn#100]
Am besten in der SAM-Template wenn es geht

**Comment by FelixBirnstiel** [comment]
Edge Functions brauchen eine CloudFront, über die nicht so einfach mit der SQS kommuniziert werden kann. Issue erstmal geschlossen, wegen wichtigeren Aufgaben. Kann bei bedarf wieder geöffnet werden.
