### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by marcmarder** [marcmarder/CloudsHandsOn#17]
- [ ] Recherche
- [ ] Tech-Demo
- [ ] Präsi 
- [ ] Evaluation

Bitte sprecht euch ab mit dem Azure Team. Die Basics müssen nicht 2-mal erklärt werden, sondern ihr teilt euch das mit Azure :).

Wir sollen beide Services recherchieren und eine Demo zu nur einem der beiden machen. 

https://github.com/marcmarder/CloudsHandsOn/issues/4 für die Template

https://docs.google.com/document/d/1GVKYsAszGhRt7L8DGo2CR4RQQT-3hf-bAba_G4IZ8AU/edit

Beanstalk und ECS

**Comment by naibafz** [comment]
Ich wollte mal fragen wie wir es aufteilen wollen?

Hatte jetzt schon mit meiner ersten Version angefangen, welche noch überarbeitet werden muss (Satzbau und Rechtschreibung und so). Da mir jetzt aber auffiel dass ich extreme Basics schreibe welche für AWS und Azure gelten wollte ich mal nachfragen.

(Text ist auch noch nicht Inhaltlich fertig, jenachdem wie tief wir gehen wollen, ob wie z.B. auf die Speicherverwaltung und Zugriffsverwaltung eingehen wollen innerhalb eines Containers mit mehreren Images)

Aktueller Text: 

Was ist ein Container technisch?

Ein Container ist ein Paket an Daten, dieses Paket besitzt dabei alle Daten die nötig sind um eine Anwendung ausführen beziehungsweise bestimmte Anfragen bearbeiten zu können. Dabei wird sich aber auf tatsächlich benötigte Daten beschränkt. Dieses Datenpaket ist aber ausführbar im Gegensatz zum Container Image, dieses ist die Vorlage nach welchem Container zur Laufzeit erstellt werden. Die Container Images selbst hingegen werden aus den Daten selbst zusammengestellt, dafür wird eine Bauanleitung benötigt welche die nötigen Daten auflistet und die zugehörigen Aktionen, diese Anleitung ist ein Dockerfile. Dabei kann ein Image auf ein bestehendes aufsetzen, dies erhöht die Wiederverwendbarkeit von Images, da so neue Images erstellt werden können von bestehenden mit kleinen Änderungen. Damit Container isoliert laufen können benötigen sie aber Betriebssystemkomponenten, beziehungsweise Teile von diesen weshalb sehr stark vereinfachte, nicht allein lauffähige Betriebssysteme, genutzt werden, welche vorher selbst in einem Image gespeichert wurden und so nutzbar und wiederverwendbar sind. So gibt es viele offizielle verfügbare Images welche verwendet werden können, um darauf aufzubauen.

%Sicherheits aspekt das man sich damit auch Viren holen kann wenn nicht offizielle Quellen


Container sind vom Host Betriebssystem abstrahiert, damit sie auf jeder Hardware und System laufen können. Als Folge dessen wird eine Software benötigt, welche die benötigten Dienste und ähnliches den Container zu Verfügung stellt, sowie deren Verwaltung übernimmt wie zum Beispiel das Skalieren von Containern, also das erstellen und löschen von diesen. Das Format der Container ist dabei standardisiert, wodurch es zur einer breiten Akzeptanz kam und sich Alternativen zum Pionier Docker entwickelten.

**Comment by naibafz** [comment]
Hier mal ein nächster Basis abschnitt bzg. VM vs Container. (Hier gilt das gleiche wie oben)

Was unterscheidet Container von VMs? 

Container und virtuelle Maschinen ähneln sich darin, dass sie es ermöglichen, Anwendungen isoliert auszuführen und skalierbar zu betreiben. Beide benötigen eine Software zur Verwaltung und zum Zugriff auf die virtualisierten Ressourcen. Bei virtuellen Maschinen geschieht dies mithilfe eines Hypervisors, während Container Container-Runtime-Engines wie Docker verwenden.  
Dennoch bestehen grundlegende Unterschiede zwischen ihnen: Virtuelle Maschinen abstrahieren die Hardware, wohingegen Container das Betriebssystem virtualisieren. Das bedeutet, dass Container das Betriebssystem des Hostsystems teilen und dessen Funktionen nutzen, wodurch sie nicht alles selbst bereitstellen müssen. Dadurch benötigen Container weniger Speicherplatz und sind leichtgewichtiger im Vergleich zu virtuellen Maschinen, die oft mehrere Gigabyte Speicherplatz beanspruchen. Tatsächlich verbrauchen Container normalerweise etwa zehn Megabyte, während virtuelle Maschinen oft mehr als zehn Gigabyte benötigen.
Diese Unterschiede führen dazu, dass Container effizienter sind, da sie weniger Ressourcen für sich in Anspruch nehmen und schneller skaliert werden können als virtuelle Maschinen.

**Comment by marcmarder** [comment]
![image](https://github.com/marcmarder/CloudsHandsOn/assets/24612516/71e6c548-8244-494a-a27c-18fc84ae502e)
