### ISSUE TITLE
Lambda

### ISSUE THREAD

**Issue by marcmarder** [marcmarder/CloudsHandsOn#18]
- [x] Recherche
- [x] Tech-Demo
- [x] Präsi 
- [x] Evaluation

Bitte sprecht euch ab mit dem Azure Team. Die Basics müssen nicht 2-mal erklärt werden, sondern ihr teilt euch das mit Azure :).

https://github.com/marcmarder/CloudsHandsOn/issues/4 für die Template

https://docs.google.com/document/d/1GVKYsAszGhRt7L8DGo2CR4RQQT-3hf-bAba_G4IZ8AU/edit

**Comment by Speedero** [comment]
Ausgabe Bierliste: https://mi0xvz47v1.execute-api.eu-central-1.amazonaws.com/beer/beerList
Ausgabe Bier Jever: https://mi0xvz47v1.execute-api.eu-central-1.amazonaws.com/beer/beerList/jever
Ausgabe Bier Herrenhäuser: https://mi0xvz47v1.execute-api.eu-central-1.amazonaws.com/beer/beerList/herrenhaeuser
