### ISSUE TITLE
Azure Functions erstellen

### ISSUE THREAD

**Issue by SDeKay** [marcmarder/CloudsHandsOn#21]
Context: Der Benutzer soll Aufgaben mit einem Formular abschicken.
1. Input Validation via Regex. HTTP Trigger
2. Aufgaben soll automatisch dem Arbeiter zugewissen werden, der am wenigsten Aufgaben hat.

**Comment by lennaht** [comment]
Wollen wir uns irgendwie absprechen, dass die unterschiedlichen Teams in ihren Services ähnliche fachliche Beispiele umsetzen? Das würde eine bessere Vergleichbarkeit bewirken.
Oder ist es besser, wenn jeder sein eigenes Ding macht, um ggf. Eigenheiten der Services besser zu beleuchten?
@thiesuss
