### ISSUE TITLE
Evaluieren AWS Services

### ISSUE THREAD

**Issue by marcmarder** [marcmarder/CloudsHandsOn#4]
Für folgende Use-Cases möchte ich die Services auf dem Blatt: 
- [x] EC2 - Virtuelle Maschinen
- [x] Functions - Lambdas
- [x] Blob Storage - S3
- [x] SQL
- [x] PubSub
- [x] Cache
- [x] Webhosting 
- [x] Queue
- [x] BlockStorage
- [x] Container Service - Elastic Beanstalk

https://docs.google.com/document/d/1T3VANTGOcRM4toV8qx28E8dvRv-9vDYdJPWjVT1EyMU/edit?usp=sharing

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-dcef17b5-7fff-61c7-cbf6-e014369b9837"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:35pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Template (kursiv - optional):</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Name |  
-- | --
Logo | Auf Folien zu finden, Größe: 1x1cm
Was macht der Service |  
Vorteile |  
Nachteile / Probleme mit dem Service |  
Was benötigt der Service |  
Welche Rahmenbedingungen gibt es |  
Gibt es Einschränkungen |  
Wie funktionieren Aufbau und Ablauf |  
Ist der Service ersetzbar |  
Welche Use Cases lassen sich damit umsetzen (Ruhig 3-4 Sätze zum Thema Versicherungssystem) |  
Fallstudie - Welches Unternehmen benutzt welchen Service wofür |  

</div><br /><br /></b>
</body>
</html>

**Comment by HsHHadi** [comment]
[Hadi] Cache + VM

**Comment by FelixBirnstiel** [comment]
[Felix] No-SQL, SQL

**Comment by Speedero** [comment]
[Basti] Lambda, Container

**Comment by FelixBirnstiel** [comment]
Ich habe die Fragen Nr.2, Nr.6, Nr.7, Nr.11 und Nr.12 weggelassen, weil ich diese schon bei Fragen davor beantworte.

**Comment by salimbouch** [comment]
[Salim] API Gateways, S3

**Comment by Tobias199711** [comment]
Queue,WebCDN

**Comment by marcmarder** [comment]
Step-Functions, PubSub (SNS)

**Comment by marcmarder** [comment]
Beanstalk
